exp_name: stage2_collector

pop: collector
ind: collector

# ====> environment config <====
env: stag_hunt
t_max: 100000  # 保持不变，最大交互时间
runner: meta  # runner 不变，用于运行环境
batch_size_run: 32
save_BR: True  # 保持True，定期保存轨迹
save_BR_episodes: 1024  # 保持不变，轨迹保存频率
population_size: 4 # modify

# ====> population config <====
alg2agent:
  controllable: [0]  # 可控智能体
  teammate: [1]  # 队友智能体

explore_alg: stage2_PP  # 探索算法保持为stage2_PP

teammate_alg: vdn
population_directories:  models/


use_history: False  # 只使用最新的模型
